target_guilds:
  # Staff Server
  - guild_id: "956715627589013576"
    reminder_channel_id: "1477819480049713324"
    relay_fields:
      - image
      - location
  # Lore Actor Server
  - guild_id: "1374811059017486356"
    reminder_channel_id: "1374814370256781442"
    relay_fields:
      - description
      - image
      - location
      - name
  # Media Team Server
  - guild_id: "1523095563829248182"
    reminder_channel_id: "1523096701257257132"
    relay_fields:
      - image
      - location

media_relay:
  source_channels:
    - "1519704066761166898"
    - "1519704018241458196"
  target_guild_id: "1523095563829248182"
  target_channel_id: "1539655545890406531"

event_name_prefix: "[PD] - "

# {event_name}, {mentions}, and {minutes} are replaced at runtime
reminder_minutes_before: 10
reminder_message: "The event **{event_name}** starts in {minutes} minutes! {mentions}"

log_level: "INFO"
